allowHostDirVolumePlugin: true
allowHostIPC: false
allowHostNetwork: true
allowHostPID: true
allowHostPorts: true
allowPrivilegeEscalation: true
allowPrivilegedContainer: false
allowedCapabilities: []
apiVersion: security.openshift.io/v1
defaultAddCapabilities: []
fsGroup:
  type: MustRunAs
groups: []
kind: SecurityContextConstraints
metadata:
  creationTimestamp: "2023-08-23T12:15:17Z"
  generation: 1
  labels:
    app: splunk-otel-collector
    app.kubernetes.io/instance: bn-logging
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: splunk-otel-collector
    app.kubernetes.io/version: 0.82.0
    chart: splunk-otel-collector-0.82.0
    helm.sh/chart: splunk-otel-collector-0.82.0
    heritage: Helm
    release: bn-logging
  name: bn-splunk
  resourceVersion: "313328962"
  uid: 4f84aa69-63d9-4dce-9445-8b74f57d52cc
priority: 10
readOnlyRootFilesystem: true
requiredDropCapabilities:
- ALL
runAsUser:
  type: RunAsAny
seLinuxContext:
  seLinuxOptions:
    level: s0
    role: system_r
    type: spc_t
    user: system_u
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:bn-logging:bn-splunk
volumes:
- configMap
- downwardAPI
- emptyDir
- hostPath
- secret
